/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.*;
import java.util.Calendar;
import java.util.ArrayList;
import DataAcessObject.*;
import java.sql.*;

/**
 *
 * @author Syl
 */
public class ajoutCours extends Header {
    
    private ArrayList<javax.swing.JCheckBox> checkBoxs;
    /**
     * Creates new form ajoutCours
     */
    public ajoutCours(Utilisateur user) {
        super(user);
        initComponents();
        
        checkBoxs.add(jCheckBoxTD1);
        checkBoxs.add(jCheckBoxTD2);
        checkBoxs.add(jCheckBoxTD3);
        checkBoxs.add(jCheckBoxTD4);
        checkBoxs.add(jCheckBoxTD5);
        checkBoxs.add(jCheckBoxTD6);
        checkBoxs.add(jCheckBoxTD7);
        checkBoxs.add(jCheckBoxTD8);
        checkBoxs.add(jCheckBoxTD9);
        checkBoxs.add(jCheckBoxTD10);
        checkBoxs.add(jCheckBoxTD11);
        checkBoxs.add(jCheckBoxTD12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMatier = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPromo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxTypeCours = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNomProf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jCheckBoxTD1 = new javax.swing.JCheckBox();
        jCheckBoxTD2 = new javax.swing.JCheckBox();
        jCheckBoxTD3 = new javax.swing.JCheckBox();
        jCheckBoxTD4 = new javax.swing.JCheckBox();
        jCheckBoxTD6 = new javax.swing.JCheckBox();
        jCheckBoxTD7 = new javax.swing.JCheckBox();
        jCheckBoxTD8 = new javax.swing.JCheckBox();
        jCheckBoxTD9 = new javax.swing.JCheckBox();
        jCheckBoxTD10 = new javax.swing.JCheckBox();
        jCheckBoxTD12 = new javax.swing.JCheckBox();
        jCheckBoxTD5 = new javax.swing.JCheckBox();
        jCheckBoxTD11 = new javax.swing.JCheckBox();
        jButtonAjourt = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldPrenomProf = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBoxHeur = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ajout de cours");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("matière:");

        jComboBoxMatier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("date:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("créneau :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("type de cours");

        jTextFieldPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPromoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("nom du professeur:");

        jComboBoxTypeCours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "magistrale", "TP", "TD", "interactif", "projet", "soutien" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("promotion des élèves:");

        jTextFieldNomProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomProfActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("groupe:");

        jCheckBoxTD1.setText("TD1");
        jCheckBoxTD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD1ActionPerformed(evt);
            }
        });

        jCheckBoxTD2.setText("TD2");
        jCheckBoxTD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD2ActionPerformed(evt);
            }
        });

        jCheckBoxTD3.setText("TD3");

        jCheckBoxTD4.setText("TD4");
        jCheckBoxTD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD4ActionPerformed(evt);
            }
        });

        jCheckBoxTD6.setText("TD6");
        jCheckBoxTD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD6ActionPerformed(evt);
            }
        });

        jCheckBoxTD7.setText("TD7");

        jCheckBoxTD8.setText("TD8");
        jCheckBoxTD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD8ActionPerformed(evt);
            }
        });

        jCheckBoxTD9.setText("TD9");

        jCheckBoxTD10.setText("TD10");
        jCheckBoxTD10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD10ActionPerformed(evt);
            }
        });

        jCheckBoxTD12.setText("TD12");
        jCheckBoxTD12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD12ActionPerformed(evt);
            }
        });

        jCheckBoxTD5.setText("TD5");
        jCheckBoxTD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD5ActionPerformed(evt);
            }
        });

        jCheckBoxTD11.setText("TD11");
        jCheckBoxTD11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD11ActionPerformed(evt);
            }
        });

        jButtonAjourt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAjourt.setText("Ajouter");
        jButtonAjourt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjourtActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("prenom:");

        jTextFieldPrenomProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomProfActionPerformed(evt);
            }
        });

        jComboBoxHeur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8h30-10h", "10h15-11h45", "12h-13h30", "13h45-15h15", "15h30-17h", "17h15-18h45", "19h-20h30" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jCheckBoxTD1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCheckBoxTD2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCheckBoxTD3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCheckBoxTD4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jCheckBoxTD7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCheckBoxTD8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCheckBoxTD9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCheckBoxTD10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCheckBoxTD5)
                                                .addComponent(jCheckBoxTD11)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(269, 269, 269)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBoxTD6)
                                        .addComponent(jCheckBoxTD12))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldPrenomProf, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNomProf, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxTypeCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxMatier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxHeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jButtonAjourt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNomProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(jTextFieldPrenomProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBoxMatier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jComboBoxHeur, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxTypeCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jCheckBoxTD1)
                    .addComponent(jCheckBoxTD2)
                    .addComponent(jCheckBoxTD3)
                    .addComponent(jCheckBoxTD4)
                    .addComponent(jCheckBoxTD6)
                    .addComponent(jCheckBoxTD5)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTD7)
                    .addComponent(jCheckBoxTD8)
                    .addComponent(jCheckBoxTD9)
                    .addComponent(jCheckBoxTD10)
                    .addComponent(jCheckBoxTD12)
                    .addComponent(jCheckBoxTD11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonAjourt)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPromoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPromoActionPerformed

    private void jTextFieldNomProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomProfActionPerformed

    private void jCheckBoxTD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD2ActionPerformed

    private void jCheckBoxTD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD4ActionPerformed

    private void jCheckBoxTD6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD6ActionPerformed

    private void jCheckBoxTD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD8ActionPerformed

    private void jCheckBoxTD10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD10ActionPerformed

    private void jCheckBoxTD12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD12ActionPerformed

    private void jCheckBoxTD5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD5ActionPerformed

    private void jCheckBoxTD11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD11ActionPerformed

    private void jButtonAjourtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjourtActionPerformed
        // TODO add your handling code here:
        Cours newCours = new Cours();
        newCours.setNom(this.jComboBoxMatier.getSelectedItem().toString());

        
        Date DateCours = new Date(jDateChooser1.getDate().getYear(), jDateChooser1.getDate().getMonth(), jDateChooser1.getDate().getDate()) ;
        
        Time heurDebut = new Time(8, 30, 0);
        switch(jComboBoxHeur.getSelectedItem().toString())
        {
            case "10h15-11h45":
            {
                heurDebut.setHours(10);
                heurDebut.setMinutes(15);
                break;
            }
            case "12h-13h30":
            {
                heurDebut.setHours(12);
                heurDebut.setMinutes(0);
                break;
            }
            case "13h45-15h15":
            {
                heurDebut.setHours(13);
                heurDebut.setMinutes(45);
                break;
            }
            case "15h30-17h":
            {
                heurDebut.setHours(15);
                heurDebut.setMinutes(30);
                break;
            }
            case "16h15-18h45":
            {
                heurDebut.setHours(16);
                heurDebut.setMinutes(15);
                break;
            }
            case "19h-20h30":
            {
                heurDebut.setHours(19);
                heurDebut.setMinutes(0);
                break;
            }           
        }
        Time heurFin = new Time(heurDebut.getHours()+1, heurDebut.getMinutes()+30, 0);
                
        Calendar cal = Calendar.getInstance();
         
        cal.set(DateCours.getYear(), DateCours.getMonth(), DateCours.getDate());
        
        int semaine = cal.get(Calendar.WEEK_OF_YEAR) - 4;
        Seance newSeance = new Seance();
        
        Type_cours typeCours = new Type_cours();
        //modifieer typeCours avec les info de jComboBoxTypeCours
        
        
        newSeance.setCours(newCours);
        newSeance.setDate(DateCours);
        newSeance.setHeure_debut(heurDebut);
        newSeance.setHeure_fin(heurFin);
        newSeance.setSemaine(semaine);
        newSeance.setType_cours(typeCours);
        
        SeanceDAO ajoutSeance = new SeanceDAO(ConnectMySQL.getInstance());
        boolean boolCreation = ajoutSeance.create(newSeance);
        
        if(false == boolCreation)
        {
            System.out.println("erreur ajoutSeance");
        }
        
        
        
        String emailProf = jTextFieldPrenomProf.getText().toString() + "." +jTextFieldNomProf.getText().toString() +"@ece.fr";
        
        EnseignantDAO rechercheProfesseur = new EnseignantDAO(ConnectMySQL.getInstance());
        
        Enseignant professeur = rechercheProfesseur.find(emailProf);
        
        Seance_enseignants  seance_enseignant = new Seance_enseignants(newSeance, professeur);
        
        Seance_enseignantsDAO ajoutSeance_enseignants = new Seance_enseignantsDAO(ConnectMySQL.getInstance());
        boolCreation = ajoutSeance_enseignants.create(seance_enseignant);
        
        if(false == boolCreation)
        {
            System.out.println("erreur ajoutSeance_enseignants");
        }
        
        Promotion promo = new Promotion();
        promo.setNom(jTextFieldPromo.getText().toString());
        
        Groupe groupe = new Groupe();
        groupe.setPromotion(promo);
        //groupe.setNom(jTextFieldTD.getText().toString());
        
        for(int compteur = 0; compteur < 12; ++compteur)
        {
            if(true == this.checkBoxs.get(compteur).isSelected())
            {
                groupe.setNom("TD" + compteur);
                
                Seance_groupes seance_groupe = new Seance_groupes(newSeance, groupe);
                
                Seance_groupesDAO ajoutSeance_groupe = new Seance_groupesDAO(ConnectMySQL.getInstance());
                boolCreation = ajoutSeance_groupe.create(seance_groupe);

                if(false == boolCreation)
                {
                    System.out.println("erreur ajoutSeance_groupe TD" + compteur);
                }
            }
        }   
        
    }//GEN-LAST:event_jButtonAjourtActionPerformed

    private void jTextFieldPrenomProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomProfActionPerformed

    private void jCheckBoxTD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], Utilisateur user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajoutCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajoutCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajoutCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajoutCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajoutCours(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjourt;
    private javax.swing.JCheckBox jCheckBoxTD1;
    private javax.swing.JCheckBox jCheckBoxTD10;
    private javax.swing.JCheckBox jCheckBoxTD11;
    private javax.swing.JCheckBox jCheckBoxTD12;
    private javax.swing.JCheckBox jCheckBoxTD2;
    private javax.swing.JCheckBox jCheckBoxTD3;
    private javax.swing.JCheckBox jCheckBoxTD4;
    private javax.swing.JCheckBox jCheckBoxTD5;
    private javax.swing.JCheckBox jCheckBoxTD6;
    private javax.swing.JCheckBox jCheckBoxTD7;
    private javax.swing.JCheckBox jCheckBoxTD8;
    private javax.swing.JCheckBox jCheckBoxTD9;
    private javax.swing.JComboBox<String> jComboBoxHeur;
    private javax.swing.JComboBox<String> jComboBoxMatier;
    private javax.swing.JComboBox<String> jComboBoxTypeCours;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldNomProf;
    private javax.swing.JTextField jTextFieldPrenomProf;
    private javax.swing.JTextField jTextFieldPromo;
    // End of variables declaration//GEN-END:variables
}
