/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Modele.*;
import java.util.Calendar;
import java.util.ArrayList;
import DataAcessObject.*;
import java.sql.*;

/**
 *
 * @author Syl
 */
public class ajoutCours extends Header {
    
    private ArrayList<javax.swing.JCheckBox> checkBoxs;
    /**
     * Creates new form ajoutCours
     */
    public ajoutCours(Utilisateur user) {
        super(user);
        initComponents();
        
        checkBoxs.add(jCheckBoxTD1);
        checkBoxs.add(jCheckBoxTD2);
        checkBoxs.add(jCheckBoxTD3);
        checkBoxs.add(jCheckBoxTD4);
        checkBoxs.add(jCheckBoxTD5);
        checkBoxs.add(jCheckBoxTD6);
        checkBoxs.add(jCheckBoxTD7);
        checkBoxs.add(jCheckBoxTD8);
        checkBoxs.add(jCheckBoxTD9);
        checkBoxs.add(jCheckBoxTD10);
        checkBoxs.add(jCheckBoxTD11);
        checkBoxs.add(jCheckBoxTD12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMatier = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMois = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAnnee = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldHeurDebut = new javax.swing.JTextField();
        jTextFieldJour = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMinsDebut = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldHeurFin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldMinsFin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPromo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxTypeCours = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNomProf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jCheckBoxTD1 = new javax.swing.JCheckBox();
        jCheckBoxTD2 = new javax.swing.JCheckBox();
        jCheckBoxTD3 = new javax.swing.JCheckBox();
        jCheckBoxTD4 = new javax.swing.JCheckBox();
        jCheckBoxTD6 = new javax.swing.JCheckBox();
        jCheckBoxTD7 = new javax.swing.JCheckBox();
        jCheckBoxTD8 = new javax.swing.JCheckBox();
        jCheckBoxTD9 = new javax.swing.JCheckBox();
        jCheckBoxTD10 = new javax.swing.JCheckBox();
        jCheckBoxTD12 = new javax.swing.JCheckBox();
        jCheckBoxTD5 = new javax.swing.JCheckBox();
        jCheckBoxTD11 = new javax.swing.JCheckBox();
        jButtonAjourt = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldPrenomProf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ajout de cours");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("matier:");

        jComboBoxMatier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("date:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("/");

        jTextFieldMois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMoisActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("/");

        jTextFieldAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnneeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("heur de debut:");

        jTextFieldHeurDebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHeurDebutActionPerformed(evt);
            }
        });

        jTextFieldJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJourActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("h");

        jTextFieldMinsDebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMinsDebutActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("min");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("heur de fin:");

        jTextFieldHeurFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHeurFinActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("h");

        jTextFieldMinsFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMinsFinActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("min");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("type de cours");

        jTextFieldPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPromoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("nom du professeur:");

        jComboBoxTypeCours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "magistrale", "TP", "TD", "interactif", "projet", "soutien" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("promotion des élèves:");

        jTextFieldNomProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomProfActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("groupe:");

        jCheckBoxTD1.setText("TD1");
        jCheckBoxTD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD1ActionPerformed(evt);
            }
        });

        jCheckBoxTD2.setText("TD2");
        jCheckBoxTD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD2ActionPerformed(evt);
            }
        });

        jCheckBoxTD3.setText("TD3");

        jCheckBoxTD4.setText("TD4");
        jCheckBoxTD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD4ActionPerformed(evt);
            }
        });

        jCheckBoxTD6.setText("TD6");
        jCheckBoxTD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD6ActionPerformed(evt);
            }
        });

        jCheckBoxTD7.setText("TD7");

        jCheckBoxTD8.setText("TD8");
        jCheckBoxTD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD8ActionPerformed(evt);
            }
        });

        jCheckBoxTD9.setText("TD9");

        jCheckBoxTD10.setText("TD10");
        jCheckBoxTD10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD10ActionPerformed(evt);
            }
        });

        jCheckBoxTD12.setText("TD12");
        jCheckBoxTD12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD12ActionPerformed(evt);
            }
        });

        jCheckBoxTD5.setText("TD5");
        jCheckBoxTD5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD5ActionPerformed(evt);
            }
        });

        jCheckBoxTD11.setText("TD11");
        jCheckBoxTD11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTD11ActionPerformed(evt);
            }
        });

        jButtonAjourt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAjourt.setText("ajouter");
        jButtonAjourt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjourtActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("prenom:");

        jTextFieldPrenomProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxMatier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHeurDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMinsDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHeurFin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMinsFin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldJour, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMois, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomProf, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addGap(0, 3, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBoxTypeCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jCheckBoxTD1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jCheckBoxTD2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jCheckBoxTD3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jCheckBoxTD4))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jCheckBoxTD7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jCheckBoxTD8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jCheckBoxTD9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jCheckBoxTD10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jCheckBoxTD5)
                                                        .addComponent(jCheckBoxTD11)))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonAjourt)
                                            .addGap(192, 192, 192)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBoxTD6)
                                        .addComponent(jCheckBoxTD12)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPrenomProf, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextFieldNomProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jTextFieldPrenomProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBoxMatier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldHeurDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextFieldMinsDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldHeurFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldMinsFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jComboBoxTypeCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jCheckBoxTD1)
                    .addComponent(jCheckBoxTD2)
                    .addComponent(jCheckBoxTD3)
                    .addComponent(jCheckBoxTD4)
                    .addComponent(jCheckBoxTD6)
                    .addComponent(jCheckBoxTD5)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTD7)
                    .addComponent(jCheckBoxTD8)
                    .addComponent(jCheckBoxTD9)
                    .addComponent(jCheckBoxTD10)
                    .addComponent(jCheckBoxTD12)
                    .addComponent(jCheckBoxTD11))
                .addGap(18, 18, 18)
                .addComponent(jButtonAjourt)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMoisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMoisActionPerformed

    private void jTextFieldAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnneeActionPerformed

    private void jTextFieldHeurDebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHeurDebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHeurDebutActionPerformed

    private void jTextFieldJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJourActionPerformed

    private void jTextFieldMinsDebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMinsDebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMinsDebutActionPerformed

    private void jTextFieldHeurFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHeurFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHeurFinActionPerformed

    private void jTextFieldMinsFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMinsFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMinsFinActionPerformed

    private void jTextFieldPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPromoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPromoActionPerformed

    private void jTextFieldNomProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomProfActionPerformed

    private void jCheckBoxTD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD2ActionPerformed

    private void jCheckBoxTD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD4ActionPerformed

    private void jCheckBoxTD6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD6ActionPerformed

    private void jCheckBoxTD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD8ActionPerformed

    private void jCheckBoxTD10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD10ActionPerformed

    private void jCheckBoxTD12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD12ActionPerformed

    private void jCheckBoxTD5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD5ActionPerformed

    private void jCheckBoxTD11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD11ActionPerformed

    private void jButtonAjourtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjourtActionPerformed
        // TODO add your handling code here:
        Cours newCours = new Cours();
        newCours.setNom(this.jComboBoxMatier.getSelectedItem().toString());

        
        int jour = Integer.parseInt(jTextFieldJour.getText().toString());
        int mois = Integer.parseInt(jTextFieldMois.getText().toString());
        int annee = Integer.parseInt(jTextFieldAnnee.getText().toString());
        
        Date DateCours = Date.valueOf(annee +"-" +mois + "-" + jour);
        
        
        int heur = Integer.parseInt(jTextFieldHeurDebut.getText().toString());        
        int min = Integer.parseInt(jTextFieldMinsDebut.getText().toString());
        
        Time heurDebut = new Time(heur, min, 0);
        
                
        heur = Integer.parseInt(jTextFieldHeurFin.getText().toString());
        min = Integer.parseInt(jTextFieldMinsFin.getText().toString());
        
        Time heurFin = new Time(heur, min, 0);
        
        
        Calendar cal = Calendar.getInstance();
         
        cal.set(annee, mois, jour);
        
        int semaine = cal.get(Calendar.WEEK_OF_YEAR) - 4;
        Seance newSeance = new Seance();
        
        newSeance.setCours(newCours);
        newSeance.setDate(DateCours);
        newSeance.setHeure_debut(heurDebut);
        newSeance.setHeure_fin(heurFin);
        newSeance.setSemaine(semaine);
        
        SeanceDAO ajoutSeance = new SeanceDAO(ConnectMySQL.getInstance());
        boolean boolCreation = ajoutSeance.create(newSeance);
        
        if(false == boolCreation)
        {
            System.out.println("erreur ajoutSeance");
        }
        
        
        
        String emailProf = jTextFieldPrenomProf.getText().toString() + "." +jTextFieldNomProf.getText().toString() +"@ece.fr";
        
        EnseignantDAO rechercheProfesseur = new EnseignantDAO(ConnectMySQL.getInstance());
        
        Enseignant professeur = rechercheProfesseur.find(emailProf);
        
        Seance_enseignants  seance_enseignant = new Seance_enseignants(newSeance, professeur);
        
        Seance_enseignantsDAO ajoutSeance_enseignants = new Seance_enseignantsDAO(ConnectMySQL.getInstance());
        boolCreation = ajoutSeance_enseignants.create(seance_enseignant);
        
        if(false == boolCreation)
        {
            System.out.println("erreur ajoutSeance_enseignants");
        }
        
        Promotion promo = new Promotion();
        promo.setNom(jTextFieldPromo.getText().toString());
        
        Groupe groupe = new Groupe();
        groupe.setPromotion(promo);
        //groupe.setNom(jTextFieldTD.getText().toString());
        
        for(int compteur = 0; compteur < 12; ++compteur)
        {
            if(true == this.checkBoxs.get(compteur).isSelected())
            {
                groupe.setNom("TD" + compteur);
                
                Seance_groupes seance_groupe = new Seance_groupes(newSeance, groupe);
                
                Seance_groupesDAO ajoutSeance_groupe = new Seance_groupesDAO(ConnectMySQL.getInstance());
                boolCreation = ajoutSeance_groupe.create(seance_groupe);

                if(false == boolCreation)
                {
                    System.out.println("erreur ajoutSeance_groupe TD" + compteur);
                }
            }
        }   
        
    }//GEN-LAST:event_jButtonAjourtActionPerformed

    private void jTextFieldPrenomProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomProfActionPerformed

    private void jCheckBoxTD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTD1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], Utilisateur user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajoutCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajoutCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajoutCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajoutCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajoutCours(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjourt;
    private javax.swing.JCheckBox jCheckBoxTD1;
    private javax.swing.JCheckBox jCheckBoxTD10;
    private javax.swing.JCheckBox jCheckBoxTD11;
    private javax.swing.JCheckBox jCheckBoxTD12;
    private javax.swing.JCheckBox jCheckBoxTD2;
    private javax.swing.JCheckBox jCheckBoxTD3;
    private javax.swing.JCheckBox jCheckBoxTD4;
    private javax.swing.JCheckBox jCheckBoxTD5;
    private javax.swing.JCheckBox jCheckBoxTD6;
    private javax.swing.JCheckBox jCheckBoxTD7;
    private javax.swing.JCheckBox jCheckBoxTD8;
    private javax.swing.JCheckBox jCheckBoxTD9;
    private javax.swing.JComboBox<String> jComboBoxMatier;
    private javax.swing.JComboBox<String> jComboBoxTypeCours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldAnnee;
    private javax.swing.JTextField jTextFieldHeurDebut;
    private javax.swing.JTextField jTextFieldHeurFin;
    private javax.swing.JTextField jTextFieldJour;
    private javax.swing.JTextField jTextFieldMinsDebut;
    private javax.swing.JTextField jTextFieldMinsFin;
    private javax.swing.JTextField jTextFieldMois;
    private javax.swing.JTextField jTextFieldNomProf;
    private javax.swing.JTextField jTextFieldPrenomProf;
    private javax.swing.JTextField jTextFieldPromo;
    // End of variables declaration//GEN-END:variables
}
